export const generateRandomColor = () => {
  const r = Math.floor(Math.random() * 250);
  const g = Math.floor(Math.random() * 250);
  const b = Math.floor(Math.random() * 250);
  const a = 0.9;
  return `rgba(${r},${g},${b},${a})`;
};

type OdiStats = {
  match: number;
  run: number;
  average: number;
  notout: number;
  highest: number | string;
  "100s": number;
  "50s": number;
  wicket: number;
  catch: number;
  ball: number;
};

// Define the type for each cricketer
export type Cricketer = {
  color: string; // Assuming generateRandomColor() returns a string
  image: string;
  dob: string; // Date of birth as a string
  fullname: string;
  odi: OdiStats;
};

export type CricketerDataType = {
  [name: string]: Cricketer;
};

export const CricketerData: CricketerDataType = {
  unknown: {
    color: generateRandomColor(),
    image: "https://via.placeholder.com/152",
    dob: "N/A",
    fullname: "Loading...",
    odi: {
      match: 0,
      run: 0,
      average: 0.0,
      notout: 0,
      highest: 0,
      "100s": 0,
      "50s": 0,
      wicket: 0,
      catch: 0,
      ball: 0,
    },
  },
  "Virat Kohli": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/val7nsa26lvpogodefwe",
    dob: "1988-11-05",
    fullname: "Virat Kohli",
    odi: {
      match: 254,
      run: 12169,
      average: 59.07,
      notout: 39,
      highest: 183,
      "100s": 43,
      "50s": 62,
      wicket: 4,
      catch: 131,
      ball: 641,
    },
  },
  "Rohit Sharma": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/xyz123",
    dob: "1987-04-30",
    fullname: "Rohit Sharma",
    odi: {
      match: 224,
      run: 9205,
      average: 48.96,
      notout: 32,
      highest: 264,
      "100s": 29,
      "50s": 43,
      wicket: 8,
      catch: 89,
      ball: 593,
    },
  },
  "KL Rahul": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/abc456",
    dob: "1992-04-18",
    fullname: "KL Rahul",
    odi: {
      match: 45,
      run: 1509,
      average: 48.67,
      notout: 5,
      highest: 112,
      "100s": 4,
      "50s": 9,
      wicket: 0,
      catch: 33,
      ball: 12,
    },
  },
  "Shubman Gill": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/sampleimageurl",
    dob: "1999-09-08",
    fullname: "Shubman Gill",
    odi: {
      match: 24,
      run: 1235,
      average: 57.23,
      notout: 3,
      highest: 208,
      "100s": 4,
      "50s": 6,
      wicket: 0,
      catch: 14,
      ball: 0,
    },
  },
  "Rishabh Pant": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/sampleimageurl",
    dob: "1997-10-04",
    fullname: "Rishabh Pant",
    odi: {
      match: 30,
      run: 865,
      average: 34.6,
      notout: 5,
      highest: 125,
      "100s": 1,
      "50s": 5,
      wicket: 0,
      catch: 28,
      ball: 0,
    },
  },
  "Shreyas Iyer": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/sampleimageurl",
    dob: "1994-12-06",
    fullname: "Shreyas Iyer",
    odi: {
      match: 42,
      run: 1631,
      average: 41.82,
      notout: 4,
      highest: 113,
      "100s": 2,
      "50s": 14,
      wicket: 0,
      catch: 20,
      ball: 0,
    },
  },
  "David Warner": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/sampleimageurl",
    dob: "1986-10-27",
    fullname: "David Warner",
    odi: {
      match: 142,
      run: 6007,
      average: 45.17,
      notout: 8,
      highest: 179,
      "100s": 18,
      "50s": 27,
      wicket: 0,
      catch: 61,
      ball: 18,
    },
  },
  "Steve Smith": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/sampleimageurl",
    dob: "1989-06-02",
    fullname: "Steve Smith",
    odi: {
      match: 128,
      run: 4378,
      average: 43.34,
      notout: 10,
      highest: 164,
      "100s": 11,
      "50s": 25,
      wicket: 28,
      catch: 62,
      ball: 990,
    },
  },
  "Kane Williamson": {
    color: generateRandomColor(),
    image:
      "https://images.icc-cricket.com/image/upload/t_ratio21_9-size60/prd/sampleimageurl",
    dob: "1990-08-08",
    fullname: "Kane Williamson",
    odi: {
      match: 151,
      run: 6173,
      average: 47.49,
      notout: 32,
      highest: 148,
      "100s": 14,
      "50s": 39,
      wicket: 29,
      catch: 60,
      ball: 1102,
    },
  },
  "Babar Azam": {
    color: generateRandomColor(),
    image: "https://example.com/babar-azam.jpg",
    dob: "1994-10-15",
    fullname: "Babar Azam",
    odi: {
      match: 80,
      run: 3808,
      average: 56.0,
      notout: 15,
      highest: 125,
      "100s": 14,
      "50s": 17,
      wicket: 2,
      catch: 27,
      ball: 212,
    },
  },
  "Joe Root": {
    color: generateRandomColor(),
    image: "https://example.com/joe-root.jpg",
    dob: "1990-12-30",
    fullname: "Joe Root",
    odi: {
      match: 149,
      run: 6104,
      average: 51.91,
      notout: 16,
      highest: 133,
      "100s": 16,
      "50s": 33,
      wicket: 26,
      catch: 60,
      ball: 1622,
    },
  },
  "Aaron Finch": {
    color: generateRandomColor(),
    image: "https://example.com/aaron-finch.jpg",
    dob: "1986-11-17",
    fullname: "Aaron Finch",
    odi: {
      match: 128,
      run: 5072,
      average: 41.82,
      notout: 9,
      highest: 153,
      "100s": 17,
      "50s": 27,
      wicket: 2,
      catch: 46,
      ball: 32,
    },
  },
  "Jonny Bairstow": {
    color: generateRandomColor(),
    image: "https://example.com/jonny-bairstow.jpg",
    dob: "1989-09-26",
    fullname: "Jonny Bairstow",
    odi: {
      match: 83,
      run: 3422,
      average: 47.25,
      notout: 8,
      highest: 141,
      "100s": 7,
      "50s": 20,
      wicket: 0,
      catch: 93,
      ball: 0,
    },
  },
  "Faf du Plessis": {
    color: generateRandomColor(),
    image: "https://example.com/faf-du-plessis.jpg",
    dob: "1984-07-13",
    fullname: "Faf du Plessis",
    odi: {
      match: 143,
      run: 5507,
      average: 45.83,
      notout: 15,
      highest: 185,
      "100s": 12,
      "50s": 35,
      wicket: 10,
      catch: 84,
      ball: 732,
    },
  },
  "Quinton de Kock": {
    color: generateRandomColor(),
    image: "https://example.com/quinton-de-kock.jpg",
    dob: "1992-12-17",
    fullname: "Quinton de Kock",
    odi: {
      match: 126,
      run: 5135,
      average: 45.54,
      notout: 12,
      highest: 178,
      "100s": 15,
      "50s": 25,
      wicket: 0,
      catch: 191,
      ball: 12,
    },
  },
  "Tamim Iqbal": {
    color: generateRandomColor(),
    image: "https://example.com/tamim-iqbal.jpg",
    dob: "1989-03-20",
    fullname: "Tamim Iqbal",
    odi: {
      match: 215,
      run: 7544,
      average: 36.74,
      notout: 10,
      highest: 158,
      "100s": 14,
      "50s": 50,
      wicket: 2,
      catch: 47,
      ball: 210,
    },
  },
  "Marnus Labuschagne": {
    color: generateRandomColor(),
    image: "https://example.com/marnus-labuschagne.jpg",
    dob: "1994-06-22",
    fullname: "Marnus Labuschagne",
    odi: {
      match: 13,
      run: 473,
      average: 39.41,
      notout: 1,
      highest: 108,
      "100s": 1,
      "50s": 2,
      wicket: 1,
      catch: 6,
      ball: 156,
    },
  },
  "Eoin Morgan": {
    color: generateRandomColor(),
    image: "https://example.com/eoin-morgan.jpg",
    dob: "1986-09-10",
    fullname: "Eoin Morgan",
    odi: {
      match: 242,
      run: 7786,
      average: 39.35,
      notout: 30,
      highest: 148,
      "100s": 14,
      "50s": 52,
      wicket: 0,
      catch: 108,
      ball: 0,
    },
  },
  "Nicholas Pooran": {
    color: generateRandomColor(),
    image: "https://example.com/nicholas-pooran.jpg",
    dob: "1995-10-02",
    fullname: "Nicholas Pooran",
    odi: {
      match: 32,
      run: 946,
      average: 31.53,
      notout: 3,
      highest: 118,
      "100s": 1,
      "50s": 5,
      wicket: 0,
      catch: 23,
      ball: 0,
    },
  },
  "Jos Buttler": {
    color: generateRandomColor(),
    image: "https://example.com/jos-buttler.jpg",
    dob: "1990-09-08",
    fullname: "Jos Buttler",
    odi: {
      match: 155,
      run: 4032,
      average: 40.32,
      notout: 22,
      highest: 150,
      "100s": 9,
      "50s": 23,
      wicket: 0,
      catch: 161,
      ball: 0,
    },
  },
  "Shimron Hetmyer": {
    color: generateRandomColor(),
    image: "https://example.com/shimron-hetmyer.jpg",
    dob: "1996-12-26",
    fullname: "Shimron Hetmyer",
    odi: {
      match: 48,
      run: 1535,
      average: 36.54,
      notout: 5,
      highest: 139,
      "100s": 3,
      "50s": 9,
      wicket: 2,
      catch: 19,
      ball: 150,
    },
  },
  "Jason Roy": {
    color: generateRandomColor(),
    image: "https://example.com/jason-roy.jpg",
    dob: "1990-07-21",
    fullname: "Jason Roy",
    odi: {
      match: 97,
      run: 3860,
      average: 40.21,
      notout: 4,
      highest: 180,
      "100s": 9,
      "50s": 20,
      wicket: 1,
      catch: 24,
      ball: 24,
    },
  },
  "Martin Guptill": {
    color: generateRandomColor(),
    image: "https://example.com/martin-guptill.jpg",
    dob: "1986-09-30",
    fullname: "Martin Guptill",
    odi: {
      match: 182,
      run: 6927,
      average: 43.57,
      notout: 11,
      highest: 237,
      "100s": 16,
      "50s": 37,
      wicket: 2,
      catch: 79,
      ball: 24,
    },
  },
  "Jasprit Bumrah": {
    color: generateRandomColor(),
    image: "https://example.com/jasprit-bumrah.jpg",
    dob: "1993-12-06",
    fullname: "Jasprit Bumrah",
    odi: {
      match: 67,
      run: 106,
      average: 10.6,
      notout: 30,
      highest: 10,
      "100s": 0,
      "50s": 0,
      wicket: 115,
      catch: 2,
      ball: 1,
    },
  },
  "Mohammed Shami": {
    color: generateRandomColor(),
    image: "https://example.com/mohammed-shami.jpg",
    dob: "1990-09-03",
    fullname: "Mohammed Shami",
    odi: {
      match: 87,
      run: 280,
      average: 10.76,
      notout: 28,
      highest: 25,
      "100s": 0,
      "50s": 0,
      wicket: 149,
      catch: 12,
      ball: 1,
    },
  },
  "Bhuvneshwar Kumar": {
    color: generateRandomColor(),
    image: "https://example.com/bhuvneshwar-kumar.jpg",
    dob: "1990-12-05",
    fullname: "Bhuvneshwar Kumar",
    odi: {
      match: 117,
      run: 632,
      average: 12.94,
      notout: 37,
      highest: 53,
      "100s": 0,
      "50s": 1,
      wicket: 138,
      catch: 35,
      ball: 9,
    },
  },
  "Ravichandran Ashwin": {
    color: generateRandomColor(),
    image: "https://example.com/ravichandran-ashwin.jpg",
    dob: "1986-09-17",
    fullname: "Ravichandran Ashwin",
    odi: {
      match: 111,
      run: 676,
      average: 14.3,
      notout: 30,
      highest: 38,
      "100s": 0,
      "50s": 0,
      wicket: 150,
      catch: 29,
      ball: 2,
    },
  },
  "Ravindra Jadeja": {
    color: generateRandomColor(),
    image: "https://example.com/ravindra-jadeja.jpg",
    dob: "1988-12-06",
    fullname: "Ravindra Jadeja",
    odi: {
      match: 170,
      run: 2412,
      average: 31.85,
      notout: 48,
      highest: 87,
      "100s": 0,
      "50s": 13,
      wicket: 187,
      catch: 85,
      ball: 6,
    },
  },
  "Trent Boult": {
    color: generateRandomColor(),
    image: "https://example.com/trent-boult.jpg",
    dob: "1989-07-22",
    fullname: "Trent Boult",
    odi: {
      match: 96,
      run: 322,
      average: 11.5,
      notout: 30,
      highest: 37,
      "100s": 0,
      "50s": 0,
      wicket: 195,
      catch: 18,
      ball: 1,
    },
  },
  "Pat Cummins": {
    color: generateRandomColor(),
    image: "https://example.com/pat-cummins.jpg",
    dob: "1993-05-08",
    fullname: "Pat Cummins",
    odi: {
      match: 69,
      run: 721,
      average: 20.6,
      notout: 17,
      highest: 36,
      "100s": 0,
      "50s": 0,
      wicket: 120,
      catch: 19,
      ball: 8,
    },
  },
  "Mitchell Starc": {
    color: generateRandomColor(),
    image: "https://example.com/mitchell-starc.jpg",
    dob: "1990-01-30",
    fullname: "Mitchell Starc",
    odi: {
      match: 97,
      run: 1026,
      average: 15.98,
      notout: 25,
      highest: 52,
      "100s": 0,
      "50s": 1,
      wicket: 184,
      catch: 22,
      ball: 4,
    },
  },
  "Kagiso Rabada": {
    color: generateRandomColor(),
    image: "https://example.com/kagiso-rabada.jpg",
    dob: "1995-05-25",
    fullname: "Kagiso Rabada",
    odi: {
      match: 79,
      run: 289,
      average: 14.45,
      notout: 22,
      highest: 31,
      "100s": 0,
      "50s": 0,
      wicket: 134,
      catch: 16,
      ball: 5,
    },
  },
  "Shaheen Afridi": {
    color: generateRandomColor(),
    image: "https://example.com/shaheen-afridi.jpg",
    dob: "2000-04-06",
    fullname: "Shaheen Afridi",
    odi: {
      match: 25,
      run: 36,
      average: 18.0,
      notout: 8,
      highest: 14,
      "100s": 0,
      "50s": 0,
      wicket: 61,
      catch: 6,
      ball: 2,
    },
  },
  "Jofra Archer": {
    color: generateRandomColor(),
    image: "https://example.com/jofra-archer.jpg",
    dob: "1995-04-01",
    fullname: "Jofra Archer",
    odi: {
      match: 14,
      run: 17,
      average: 8.5,
      notout: 6,
      highest: 6,
      "100s": 0,
      "50s": 0,
      wicket: 23,
      catch: 3,
      ball: 1,
    },
  },
  "Josh Hazlewood": {
    color: generateRandomColor(),
    image: "https://example.com/josh-hazlewood.jpg",
    dob: "1991-01-08",
    fullname: "Josh Hazlewood",
    odi: {
      match: 61,
      run: 95,
      average: 13.57,
      notout: 20,
      highest: 11,
      "100s": 0,
      "50s": 0,
      wicket: 104,
      catch: 12,
      ball: 4,
    },
  },
  "Lockie Ferguson": {
    color: generateRandomColor(),
    image: "https://example.com/lockie-ferguson.jpg",
    dob: "1991-06-13",
    fullname: "Lockie Ferguson",
    odi: {
      match: 35,
      run: 34,
      average: 8.5,
      notout: 9,
      highest: 19,
      "100s": 0,
      "50s": 0,
      wicket: 69,
      catch: 10,
      ball: 1,
    },
  },
  "Anrich Nortje": {
    color: generateRandomColor(),
    image: "https://example.com/anrich-nortje.jpg",
    dob: "1993-11-16",
    fullname: "Anrich Nortje",
    odi: {
      match: 16,
      run: 16,
      average: 16.0,
      notout: 6,
      highest: 9,
      "100s": 0,
      "50s": 0,
      wicket: 33,
      catch: 0,
      ball: 1,
    },
  },
  "Rashid Khan": {
    color: generateRandomColor(),
    image: "https://example.com/rashid-khan.jpg",
    dob: "1998-09-20",
    fullname: "Rashid Khan",
    odi: {
      match: 77,
      run: 871,
      average: 18.29,
      notout: 18,
      highest: 60,
      "100s": 0,
      "50s": 2,
      wicket: 141,
      catch: 18,
      ball: 7,
    },
  },
  "Adil Rashid": {
    color: generateRandomColor(),
    image: "https://example.com/adil-rashid.jpg",
    dob: "1988-02-17",
    fullname: "Adil Rashid",
    odi: {
      match: 106,
      run: 661,
      average: 17.39,
      notout: 22,
      highest: 69,
      "100s": 0,
      "50s": 2,
      wicket: 147,
      catch: 24,
      ball: 1,
    },
  },
  "Mustafizur Rahman": {
    color: generateRandomColor(),
    image: "https://example.com/mustafizur-rahman.jpg",
    dob: "1995-09-06",
    fullname: "Mustafizur Rahman",
    odi: {
      match: 69,
      run: 144,
      average: 14.4,
      notout: 20,
      highest: 18,
      "100s": 0,
      "50s": 0,
      wicket: 126,
      catch: 9,
      ball: 4,
    },
  },
  "Mark Wood": {
    color: generateRandomColor(),
    image: "https://example.com/mark-wood.jpg",
    dob: "1990-01-11",
    fullname: "Mark Wood",
    odi: {
      match: 56,
      run: 187,
      average: 10.94,
      notout: 19,
      highest: 33,
      "100s": 0,
      "50s": 0,
      wicket: 65,
      catch: 13,
      ball: 9,
    },
  },
  "Nathan Lyon": {
    color: generateRandomColor(),
    image: "https://example.com/nathan-lyon.jpg",
    dob: "1987-11-20",
    fullname: "Nathan Lyon",
    odi: {
      match: 29,
      run: 130,
      average: 16.25,
      notout: 9,
      highest: 30,
      "100s": 0,
      "50s": 0,
      wicket: 32,
      catch: 8,
      ball: 1,
    },
  },
  "Imran Tahir": {
    color: generateRandomColor(),
    image: "https://example.com/imran-tahir.jpg",
    dob: "1979-03-27",
    fullname: "Imran Tahir",
    odi: {
      match: 107,
      run: 213,
      average: 9.69,
      notout: 31,
      highest: 29,
      "100s": 0,
      "50s": 0,
      wicket: 173,
      catch: 15,
      ball: 1,
    },
  },
  "Mitchell Santner": {
    color: generateRandomColor(),
    image: "https://example.com/mitchell-santner.jpg",
    dob: "1992-02-05",
    fullname: "Mitchell Santner",
    odi: {
      match: 75,
      run: 782,
      average: 24.43,
      notout: 17,
      highest: 67,
      "100s": 0,
      "50s": 4,
      wicket: 84,
      catch: 27,
      ball: 4,
    },
  },
  "Shakib Al Hasan": {
    color: generateRandomColor(),
    image: "https://example.com/shakib-al-hasan.jpg",
    dob: "1987-03-24",
    fullname: "Shakib Al Hasan",
    odi: {
      match: 206,
      run: 6323,
      average: 37.86,
      notout: 27,
      highest: 134,
      "100s": 9,
      "50s": 47,
      wicket: 270,
      catch: 80,
      ball: 3,
    },
  },
};
